package edu.school21;

public enum ConversationState {
    NONE,
    AWAITING_NEW_CATEGORY,
    AWAITING_EXPENSE_AMOUNT,
    AWAITING_DATE_START,
    AWAITING_DATE_FINISH,
    AWAITING_EXPENSE_ABSTRACT,
    AWAITING_PRAYER_CITY,
    AWAITING_ID_TO_DELETE
}
